# Generated by Django 5.1.3 on 2025-11-11 22:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=30)),
                ('exam_length', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('course_code', models.CharField(max_length=30)),
                ('exam_type', models.CharField(max_length=30)),
                ('no_students', models.IntegerField()),
                ('exam_school', models.CharField(max_length=30)),
                ('date_exam', models.DateField()),
                ('school_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('venuetype', models.CharField(choices=[('main_hall', 'Main Hall'), ('purple_cluster', 'Purple Cluster'), ('computer_cluster', 'Computer Cluster'), ('separate_room', 'Separate Room'), ('school_to_sort', 'School To Sort')], max_length=30)),
                ('is_accessible', models.BooleanField(default=True)),
                ('qualifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Provisions',
            fields=[
                ('provision_id', models.AutoField(primary_key=True, serialize=False)),
                ('provisions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('extra_time', 'Extra Time'), ('computer_needed', 'Computer Needed'), ('reader', 'Reader'), ('scribe', 'Scribe')], max_length=30), blank=True, null=True, size=None)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamVenue',
            fields=[
                ('examvenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('adj_starttime', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.venue')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
